version: '3.8'  # Asegúrate de usar la versión de Docker Compose adecuada

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2  # Última versión de Elasticsearch
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # Desactivar seguridad para pruebas
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Exponer el puerto 9200
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
